### ISSUE TITLE
Cannot get Svara marks working with gM & ggM symbols

### ISSUE THREAD

**Issue by arunagirinathar** [Sandhi-IITBombay/Shobhika#14]
Namaste,

This is probably peculiar to the Taittiriya recession of the Krishna Yajurveda - gM and gg with svarita/anudatta. Cannot get a agamanunasika conjunct with svarita / anudatta. Screen shot attached below for reference.

![gm_gg](https://user-images.githubusercontent.com/6995292/58369340-af62b300-7f16-11e9-98ce-363d100bae1d.png)

If I am not doing it right -- please guide.

Also the conjuncts - gM & ggM do not occur in regular classical sanskrit, to the best of my knowledge since these are exclusively used in the Yajurveda. It would be of great help to make g+M & g+g+M combination point to the vedic symbols respectively (if possible).

Thank you again.

**Comment by ijya** [comment]
Hi,

This works for me:
![image](https://user-images.githubusercontent.com/14329604/58411752-a139a180-8092-11e9-9840-3998e14767eb.png)

Try pasting the following sequence: ꣳ॑ ꣳ᳚ ꣳ॒ ꣴ॑ ꣴ᳚ ꣴ॒ and let me know the result.

**Comment by arunagirinathar** [comment]
Got all of the conjuncts except the first one (?). Attached is a screen shot below -- (Compatibility issues ?) -- tested this on LibreOffice 5.4.7 on a Windows 10 Machine.

![Shobhika_gMggM](https://user-images.githubusercontent.com/6995292/58429520-c98dc400-80c3-11e9-8542-19795ef436c1.png)

Also the glyphs highlighted in red are useless since  they **not** occur in any of the extant Yajurveda schools (Shukla or Krishna).

**Comment by ijya** [comment]
Closing this as solved. I am sure you were able to figure out the issue with the first character.

**Comment by arunagirinathar** [comment]
Namaste Jee,

Thank you very much for the update. As for Samaveda Svaras, if this project is still alive, I have contacted a Samaveda Adhyayi who is willing to share the knowledge of Samaveda Swaras and their positioning in various contexts - for the Kauthuma and Jaiminiya Shakhas.

Please reply as to whether I can put him in correspondence with you through Email or Github, whichever suits you.

**Comment by ijya** [comment]
Thanks for the offer. We may get in touch with you later to implement the same.
