### ISSUE TITLE
Italic shobhika

### ISSUE THREAD

**Issue by tristancurteis** [Sandhi-IITBombay/Shobhika#15]
It would be very nice for shobhika to be available in italics.

**Comment by tristancurteis** [comment]
I should add - shobhika is a very beautiful font, so thank you.

**Comment by ijya** [comment]
@tristancurteis Thanks for the feedback! Shobhika has been primarily designed for academic publishing, where we do not feel there is any compelling use case for an italics variant. Hence, we have no plans to develop an italics variant of Shobhika. Under the circumstances, I will be closing this issue as it is beyond the scope of our project.
