### ISSUE TITLE
Any help on input software

### ISSUE THREAD

**Issue by hvina** [Sandhi-IITBombay/Shobhika#16]
Can you point us to any method that can be used for inputting .
 I am using Ubuntu 18.04and would like some ways of starting to type. Can you point to some ways of getting started

**Comment by ijya** [comment]
You can use the Sanskrit KaGaPa Keyboard given in Ubuntu. Go to the Region and Language settings and add this keyboard. Once the keyboard is added, you can switch between keyboard in the top panel and also view the keyboard layout and familiarise yourself. The Readme points to a link with a more detailed description.

**Comment by hvina** [comment]
Thanks . I used the Sanskrit KaGaPa keyboard . One issue that I faced . Would like to see if you have a better suggestion .
I wanted to type अ॒ ( anudatta ) . So I type in (Alt-Gr A) and then i have to switch the keyboard to English and then type Ctrl+Shift+U0952 for the audatta [ since the u does not work in the KaGaPa keyboard ] .
Is there a better way to do this ?

**Comment by ijya** [comment]
Anudatta and Svarita are already part of the KaGaPa Sanskrit Keyboard and are mapped to AltGr + - (minus sign) and AltGr + ' (apostrophe) respectively. Please check the keyboard layout carefully. For other vedic symbols, you may either use the hexadecimal input as you are doing, or create your own custom keyboard layout as described here: [https://help.ubuntu.com/community/Custom%20keyboard%20layout%20definitions](url)

**Comment by hvina** [comment]
Thank you @ijya

**Comment by vrgovinda** [comment]
There is no AltGR in my laptop keyboard. How can I use the KaGaPa input method? It requires this key very often. Can you help me out?

**Comment by ijya** [comment]
AltGR is simply the right Alt key.
