### ISSUE TITLE
Any guideline for writing pluta swaras ?

### ISSUE THREAD

**Issue by hvram1** [Sandhi-IITBombay/Shobhika#17]
Is there a guideline for writing pluta swaras ? I can see a U1CE1 denoted as vaidika svarita dvi vakra khannda . which comes as ᳡ , I am trying to write ( अयमॆकॊ᳡वशिष्टॊ᳡स्मित्यॆवमावाहयॆच्छिवम् ) . Is this the correct way ?

**Comment by ijya** [comment]
Not an expert on this topic. Please enquire elsewhere.

**Comment by ijya** [comment]
Closing the topic.
