### ISSUE TITLE
Unable to type some characters

### ISSUE THREAD

**Issue by hrishim** [Sandhi-IITBombay/Shobhika#18]
![example](https://user-images.githubusercontent.com/8455532/144362646-152af85b-1cde-473c-b896-050718f18cac.png)

Unable to type the RUU or TRUU etc. Please see image that shows the text I am unable to write.

**Comment by ijya** [comment]
This is not a font issue. Please refer to the "Typing special characters" section of the readme file. In short, you either have to create your own custom keyboard layout, or use hexadecimal input for characters not found on your standard Devanagari keyboard.
