### ISSUE TITLE
Visarga in Akshara with/without Vedic-Svara

### ISSUE THREAD

**Issue by RumaDewan** [Sandhi-IITBombay/Shobhika#20]
the visarga following akshara with vedic-svara 
appear differently from
the visarga following akshara without vedic-svara

[MS Word]

![image](https://user-images.githubusercontent.com/107683995/174755121-aaaeaf5d-3386-4234-95c1-f1a231315289.png)

**Comment by ijya** [comment]
You have to type the visarga before the svara.

**Comment by RumaDewan** [comment]
> You have to type the visarga before the svara.

before n after results

![image](https://user-images.githubusercontent.com/107683995/174856436-49f1b7a5-5872-4952-9d7f-06d35c47ddf8.png)

**Comment by RumaDewan** [comment]
since the issue is showing as "Closed", I am reposting as new.
