### ISSUE TITLE
Issue with some Consonant Clusters on mac

### ISSUE THREAD

**Issue by vidyajay** [Sandhi-IITBombay/Shobhika#3]
@ijya There are a few issues with clusters such as: 
(i) repha over a vowel following three consonant (try)
(ii) Candrabindu over a half-y or half-v 

The repha issue does not occur on Windows but only occurs on OS X (so far tested with Yosemite and MountainLion) and Nisus writer Pro.  Is there an email contact to whom a non-GIThub Sanskrit expert can send specific consonant cluster issues they come across as they use the font?

**Comment by ijya** [comment]
@vidyajay 
Give me some time to investigate the issue. Emails can be sent to the Project Lead (Aditya) whose contact you will find in the CONTRIBUTORS.txt file

**Comment by ijya** [comment]
@vidyajay The above issues are fixed in the new release v1.04
