### ISSUE TITLE
anudatta

### ISSUE THREAD

**Issue by karthik-holla** [Sandhi-IITBombay/Shobhika#4]
The anudatta svara symbol for ह्रस्व इकार and दीर्घ ईकार are not consistent.

**Comment by ijya** [comment]
@karthik-holla Can you please share a few examples? Also please give details of OS and application being used.

**Comment by karthik-holla** [comment]
I am using Slackware linux and Libreoffice-5.2.4. I have attached a pdf file. Thanks
[anudatta_problem.pdf](https://github.com/Sandhi-IITBombay/Shobhika/files/715946/anudatta_problem.pdf)

**Comment by ijya** [comment]
@karthik-holla These bugs have been fixed in the just released v1.04

**Comment by gasyoun** [comment]
@ijya thanks!
