### ISSUE TITLE
Package Shobhika for Debian/Hamara Linux

### ISSUE THREAD

**Issue by rajudev** [Sandhi-IITBombay/Shobhika#7]
![selection_010](https://user-images.githubusercontent.com/2010120/31670640-a99da236-b375-11e7-9d56-68f208401a2a.png)

I noticed this today. 
Someone from your side was looking to package Shobhika for Debian and wanted help. 
I can help with that, you can also consider an immediate package for Shobhika in [`Hamara Linux`](https://www.hamaralinux.org/) aka the homegrown Indian Linux Distribution. You can make Shobhika immediately available with Hamara Linux and in a short span of time also in Debian. I can help you regarding this. Lets discuss about it, over this issue.

**Comment by ijya** [comment]
@rajudev , I posted the request on ```#debian-mentors``` and ```#debian-in```. We want to make Shobhika as widely accessible as possible, but need help packaging it for different distros. Let me know how to proceed.

**Comment by rajudev** [comment]
Do you need help, packaging the font yourself? or do you need someone else to do it for you? 

There are many packaging guidelines available for you to learn from. But I guess id would be better if you can follow along instructions by asking on our IRC channel. 
You can hang around at #hamara on OFTC or on #debian-in on OFTC for communicating with us.

**Comment by rajudev** [comment]
how am I supposed to get this done, if you do not communicate properly regarding what you want to do, and go on closing the issues, without an update..

**Comment by ijya** [comment]
Apologies. The font has already been packaged for Fedora and Debian is being taken care of. Please let us know if you could help us package it for Hamara Linux.

**Comment by Shreeshrii** [comment]
What is the package name to use it in Ubuntu?

**Comment by ijya** [comment]
@Shreeshrii  The package is not in Ubuntu yet. You can download the font directly from the releases page. One it is packaged for Debian, hopefully it will get pulled in by Ubuntu too. 

@rajudev Can you package the font for Debian? The person who was supposed to do this is caught up with some other work. Your help will be greatly appreciated. I have already created a bug report here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=886300

**Comment by Shreeshrii** [comment]
Maybe too late now for Ubuntu 18.04

**Comment by rajudev** [comment]
@Shreeshrii @ijya I am happy to do it. Let me update about the packaging status in a while. 
Although it's late for Ubuntu 18.04, but if we do it soon, we'll catch the 18.10 release.

**Comment by copyninja** [comment]
Just to put it here I noticed that font is produced using fontlab and is in .vfb format. Debian normally has policy to build font from source and the use of propreitary version prevents us from packaging this font. It would be good if upstream can switch to free software tools for producing the font. 

This was provided to me on #debian-fonts IRC http://robofab.org/howto/makeufo.html may be this can be used by upstream?

**Comment by ijya** [comment]
@copyninja Thanks for pointing this out. At this stage, we do not have the resources to make this conversion. I appreciate your help. I will close this issue now and reopen it later if we manage to build the font as per Debian guidelines.

@rajudev You may package for Hamara Linux at your end. As this is not a font issue, I am closing this topic.

**Comment by Manas-kashyap** [comment]
Well i have taken this task for packaging shobhika ,
