### ISSUE TITLE
Request to update zip file release

### ISSUE THREAD

**Issue by pnemade** [Sandhi-IITBombay/Shobhika#8]
I see that zip file only provides binary font files but there is no other files in zip file. It is a good practice to add license file along with any other documentation files in the released archives.

I request to add all the *.txt files along with README.md file.

**Comment by pnemade** [comment]
Also, Zip file when extracted should create directory as %{name}-%{version} that is for this project it should extract Shobhika-1.04 directory and all files extracted inside this directory.

**Comment by ijya** [comment]
Done.
